## Model sekwencjny (Sequential Model):
### Załadowanie bibliotek

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

'2.1.0'

### <a name='a0'></a>Wprowadzenie - pierwszy model
Model sekwencyjny to nic innego jak liniowy stos warstw.

In [4]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy **Dense**. Aby dodać warstwę do modelu należy użyć metody *.add()*

In [5]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

Wyświetlenie podsumowania modelu: metoda.summary()

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 44        
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


Dodanie kolejnej warstwy

In [7]:
model.add(Dense(units=2))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 44        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 10        
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


### <a name='a1'></a>Funkcje aktywacji
Istotnym elemenem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja aktywacji, tzn. $a(x)=x$

Warstwa z liniową funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji aby rozwiazywać problemy nieliniowe.

[Keras: Funkcje aktywacji](https://keras.io/activations/)

In [11]:
from tensorflow.keras.activations import linear

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [12]:
px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3,3])

In [13]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [15]:
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-.5,1.5])

In [16]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [18]:
px.line(data, x='data', y='relu', width=500, height=400, range_y=[-.5, 1.5])

In [19]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [22]:
px.line(data, x='data', y='tanh', width=500, height=400, range_y=[-1.5, 1.5])

In [23]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


### <a name='a2'></a>Kompilacja modelu
Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:
* rodzaj optymalizatora ([Keras - Optymalizatory](https://keras.io/optimizers/)) 
* funkcję straty ([Keras - Funkcje Straty](https://keras.io/losses/))
* metryki, które będziemy obserwować podczas trenowania sieci ([Keras - Metryki](https://keras.io/metrics/))

In [24]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

### <a name='a3'></a>Trenowanie modelu
Za dane wejściowe do modelu należy przekazać Numpy arrays:
* **epochs** - krotność przejścia danych przez sieć w procesie uczenia
* **batch_size** - rozmiar wsadu po którym następuje aktualizacja wag
* **validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
* **validation_data** - (x_val, y_val) - dane wykorzystane do walidacji modelu

In [ ]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

### <a name='a4'></a> Przykład - klasyfikacja binarna

In [25]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000,1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [26]:
data[:3]

array([[ 4.35630971e-01,  8.04334565e-01, -1.60161266e+00,
        -8.27870237e-01,  2.03658816e-01,  1.39264984e+00,
        -1.05951283e+00,  8.56362364e-01,  1.53756780e+00,
        -1.84159202e+00, -1.18459570e+00,  1.31073727e-01,
        -3.84246111e-01, -1.52956501e-01,  5.22425361e-01,
        -1.26062376e-02,  3.98477224e-01, -9.52652577e-01,
         2.45152444e-01, -1.01120431e+00, -5.37597394e-01,
         1.02957790e+00, -2.40505940e+00,  1.69654502e-01,
         3.07640488e-01, -5.03029120e-01, -7.35260492e-01,
         1.89249946e+00,  8.26232175e-01,  7.78073095e-01,
         7.71020633e-02,  2.67726139e-01,  1.54928777e-01,
        -6.87448342e-01,  1.01464812e+00, -2.64389770e-01,
         1.04589515e+00,  2.89341225e-01, -4.60615882e-01,
        -4.90001279e-01, -1.46669942e+00, -5.69921199e-02,
         6.23500530e-01, -5.52849824e-01,  7.91657629e-01,
         1.59807519e+00,  3.56992121e-01, -2.13295593e-01,
         1.28887257e-01,  1.83689673e+00,  3.28657912e-0

In [27]:
labels[:10]

array([[0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1]])

In [29]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Train on 10000 samples
Epoch 1/20
10000/10000 [==============================] - 1s 68us/sample - loss: 0.7442 - accuracy: 0.5019
Epoch 2/20
10000/10000 [==============================] - 0s 36us/sample - loss: 0.6931 - accuracy: 0.5402
Epoch 3/20
10000/10000 [==============================] - 0s 35us/sample - loss: 0.6784 - accuracy: 0.5687
Epoch 4/20
10000/10000 [==============================] - 0s 38us/sample - loss: 0.6664 - accuracy: 0.5945
Epoch 5/20
10000/10000 [==============================] - 0s 42us/sample - loss: 0.6546 - accuracy: 0.6179
Epoch 6/20
10000/10000 [==============================] - 0s 44us/sample - loss: 0.6426 - accuracy: 0.6354
Epoch 7/20
10000/10000 [==============================] - 0s 39us/sample - loss: 0.6288 - accuracy: 0.6508
Epoch 8/20
10000/10000 [==============================] - 0s 39us/sample - loss: 0.6154 - accuracy: 0.6702
Epoch 9/20
10000/10000 [==============================] - 0s 41us/sample - loss: 0.6011 - accuracy: 0.6853
Epoch 10/20
10

In [30]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

Train on 10000 samples
Epoch 1/20
10000/10000 [==============================] - 1s 65us/sample - loss: 0.7578 - accuracy: 0.4983
Epoch 2/20
10000/10000 [==============================] - 0s 20us/sample - loss: 0.7000 - accuracy: 0.5408
Epoch 3/20
10000/10000 [==============================] - 0s 21us/sample - loss: 0.6828 - accuracy: 0.5663
Epoch 4/20
10000/10000 [==============================] - 0s 20us/sample - loss: 0.6704 - accuracy: 0.5876
Epoch 5/20
10000/10000 [==============================] - 0s 17us/sample - loss: 0.6596 - accuracy: 0.6037
Epoch 6/20
10000/10000 [==============================] - 0s 21us/sample - loss: 0.6492 - accuracy: 0.6237
Epoch 7/20
10000/10000 [==============================] - 0s 22us/sample - loss: 0.6389 - accuracy: 0.6413
Epoch 8/20
10000/10000 [==============================] - 0s 21us/sample - loss: 0.6289 - accuracy: 0.6512
Epoch 9/20
10000/10000 [==============================] - 0s 20us/sample - loss: 0.6186 - accuracy: 0.6657
Epoch 10/20
10

In [31]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Train on 8000 samples, validate on 2000 samples
Epoch 1/20
8000/8000 [==============================] - 1s 88us/sample - loss: 0.7847 - accuracy: 0.5034 - val_loss: 0.7311 - val_accuracy: 0.4990
Epoch 2/20
8000/8000 [==============================] - 0s 45us/sample - loss: 0.7015 - accuracy: 0.5393 - val_loss: 0.7240 - val_accuracy: 0.5065
Epoch 3/20
8000/8000 [==============================] - 0s 42us/sample - loss: 0.6769 - accuracy: 0.5765 - val_loss: 0.7264 - val_accuracy: 0.5025
Epoch 4/20
8000/8000 [==============================] - 0s 41us/sample - loss: 0.6583 - accuracy: 0.6066 - val_loss: 0.7294 - val_accuracy: 0.5025
Epoch 5/20
8000/8000 [==============================] - 0s 42us/sample - loss: 0.6424 - accuracy: 0.6294 - val_loss: 0.7340 - val_accuracy: 0.4980
Epoch 6/20
8000/8000 [==============================] - 0s 43us/sample - loss: 0.6258 - accuracy: 0.6545 - val_loss: 0.7421 - val_accuracy: 0.5025
Epoch 7/20
8000/8000 [==============================] - 0s 42us/sample

In [34]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=.2, verbose=0)

In [35]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [36]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=.2, verbose=1)

Train on 8000 samples, validate on 2000 samples
Epoch 1/20
8000/8000 [==============================] - 1s 89us/sample - loss: 0.7346 - accuracy: 0.5009 - val_loss: 0.7124 - val_accuracy: 0.5100
Epoch 2/20
8000/8000 [==============================] - 0s 42us/sample - loss: 0.6904 - accuracy: 0.5445 - val_loss: 0.7096 - val_accuracy: 0.5180
Epoch 3/20
8000/8000 [==============================] - 0s 43us/sample - loss: 0.6737 - accuracy: 0.5813 - val_loss: 0.7135 - val_accuracy: 0.5065
Epoch 4/20
8000/8000 [==============================] - 0s 40us/sample - loss: 0.6603 - accuracy: 0.5994 - val_loss: 0.7170 - val_accuracy: 0.4945
Epoch 5/20
8000/8000 [==============================] - 0s 42us/sample - loss: 0.6471 - accuracy: 0.6250 - val_loss: 0.7217 - val_accuracy: 0.4985
Epoch 6/20
8000/8000 [==============================] - ETA: 0s - loss: 0.6328 - accuracy: 0.64 - 0s 49us/sample - loss: 0.6322 - accuracy: 0.6457 - val_loss: 0.7259 - val_accuracy: 0.5035
Epoch 7/20
8000/8000 [======

In [37]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5,1))

In [38]:
model.predict(test_data)

array([[0.11637262],
       [0.26846376],
       [0.8783969 ],
       [0.00857869],
       [0.4743931 ]], dtype=float32)

In [39]:
model.predict_proba(test_data)

array([[0.11637262],
       [0.26846376],
       [0.8783969 ],
       [0.00857869],
       [0.4743931 ]], dtype=float32)

In [40]:
model.predict_classes(test_data)

array([[0],
       [0],
       [1],
       [0],
       [0]])

### <a name='a4'></a> Przykład - klasyfikacja wieloklasowa

In [43]:
data = np.random.random((10000,150))
labels = np.random.randint(10, size=(10000,1))

In [44]:
print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [45]:
labels[:10]

array([[4],
       [0],
       [6],
       [5],
       [7],
       [4],
       [3],
       [9],
       [0],
       [8]])

In [46]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [47]:
labels[1]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [49]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=.2)

Train on 8000 samples, validate on 2000 samples
Epoch 1/30
8000/8000 [==============================] - 1s 89us/sample - loss: 2.3167 - accuracy: 0.1018 - val_loss: 2.3012 - val_accuracy: 0.1055
Epoch 2/30
8000/8000 [==============================] - 0s 45us/sample - loss: 2.3039 - accuracy: 0.0980 - val_loss: 2.3015 - val_accuracy: 0.1005
Epoch 3/30
8000/8000 [==============================] - 0s 43us/sample - loss: 2.3014 - accuracy: 0.1058 - val_loss: 2.3049 - val_accuracy: 0.1015
Epoch 4/30
8000/8000 [==============================] - 0s 44us/sample - loss: 2.3011 - accuracy: 0.1067 - val_loss: 2.3064 - val_accuracy: 0.0985
Epoch 5/30
8000/8000 [==============================] - 0s 43us/sample - loss: 2.2970 - accuracy: 0.1096 - val_loss: 2.3040 - val_accuracy: 0.1005
Epoch 6/30
8000/8000 [==============================] - 0s 42us/sample - loss: 2.2934 - accuracy: 0.1187 - val_loss: 2.3117 - val_accuracy: 0.1145
Epoch 7/30
8000/8000 [==============================] - 0s 44us/sample

In [50]:
test_data = np.random.random((10,150))

model.predict(test_data)

array([[0.13472542, 0.03315946, 0.09017222, 0.14145923, 0.16044137,
        0.05240156, 0.03446042, 0.11340631, 0.16694345, 0.07283066],
       [0.08352854, 0.04043718, 0.0230252 , 0.21278347, 0.13199072,
        0.09815179, 0.02094826, 0.26433983, 0.06310153, 0.06169346],
       [0.10016339, 0.10753781, 0.10051288, 0.10429893, 0.06461684,
        0.09875035, 0.13716452, 0.06870792, 0.12469307, 0.0935543 ],
       [0.07842725, 0.08869448, 0.12960814, 0.08111046, 0.0776199 ,
        0.1107759 , 0.10855819, 0.09744423, 0.11235475, 0.11540667],
       [0.14831159, 0.04090558, 0.1046259 , 0.10408407, 0.04701413,
        0.08617817, 0.11179297, 0.13019234, 0.14344622, 0.08344898],
       [0.12521459, 0.06423176, 0.07935656, 0.07717305, 0.18356955,
        0.06331667, 0.01335635, 0.0887595 , 0.1105131 , 0.19450887],
       [0.07191213, 0.14626326, 0.17186356, 0.03547899, 0.12073679,
        0.12245429, 0.11367311, 0.05006234, 0.06773242, 0.09982309],
       [0.16272847, 0.0539724 , 0.0865207

In [51]:
model.predict_classes(test_data)

array([8, 7, 6, 2, 0, 9, 2, 6, 3, 2], dtype=int64)

### <a name='a4'></a> Przykład - regresja

In [56]:
data = np.random.random((10000,150))
labels = 50 * np.random.random(10000)

In [57]:
labels[:10]

array([11.26948216,  4.832883  , 46.11765354, 27.83153034, 22.24325633,
       49.88623095,  8.50155117,  6.67583607, 43.45839847, 34.25095284])

In [58]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=.2)

Train on 8000 samples, validate on 2000 samples
Epoch 1/30
8000/8000 [==============================] - 1s 68us/sample - loss: 273.4261 - val_loss: 213.9547
Epoch 2/30
8000/8000 [==============================] - 0s 35us/sample - loss: 214.3775 - val_loss: 213.8855
Epoch 3/30
8000/8000 [==============================] - 0s 39us/sample - loss: 213.8279 - val_loss: 214.7934
Epoch 4/30
8000/8000 [==============================] - 0s 39us/sample - loss: 213.6895 - val_loss: 214.3852
Epoch 5/30
8000/8000 [==============================] - 0s 47us/sample - loss: 213.3947 - val_loss: 213.9545
Epoch 6/30
8000/8000 [==============================] - 0s 39us/sample - loss: 212.8779 - val_loss: 214.4562
Epoch 7/30
8000/8000 [==============================] - 0s 47us/sample - loss: 212.6901 - val_loss: 214.2323
Epoch 8/30
8000/8000 [==============================] - 0s 42us/sample - loss: 212.4367 - val_loss: 215.1953
Epoch 9/30
8000/8000 [==============================] - 0s 45us/sample - loss: 2

In [59]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=10, batch_size=32, validation_split=.2)

Train on 8000 samples, validate on 2000 samples
Epoch 1/10
8000/8000 [==============================] - 1s 84us/sample - loss: 13.8171 - mse: 271.2982 - val_loss: 12.7902 - val_mse: 215.0061
Epoch 2/10
8000/8000 [==============================] - 0s 42us/sample - loss: 12.7168 - mse: 214.6657 - val_loss: 12.7873 - val_mse: 215.0054
Epoch 3/10
8000/8000 [==============================] - 0s 43us/sample - loss: 12.7030 - mse: 214.4186 - val_loss: 12.7860 - val_mse: 214.8740
Epoch 4/10
8000/8000 [==============================] - 0s 41us/sample - loss: 12.6888 - mse: 214.1197 - val_loss: 12.7878 - val_mse: 215.0116
Epoch 5/10
8000/8000 [==============================] - 0s 40us/sample - loss: 12.6681 - mse: 213.6576 - val_loss: 12.8592 - val_mse: 219.8014
Epoch 6/10
8000/8000 [==============================] - 0s 43us/sample - loss: 12.6696 - mse: 213.8467 - val_loss: 12.7920 - val_mse: 215.9265
Epoch 7/10
8000/8000 [==============================] - 0s 42us/sample - loss: 12.6452 - mse: 

In [ ]:
test_data = n