## Basic array operations

In [2]:
import numpy as np

In [4]:
A = np.array([1,2,3,4])
B = np.array([5,6,7,8])
print(A)
print(B)

[1 2 3 4]
[5 6 7 8]


In [5]:
A + B

array([ 6,  8, 10, 12])

In [6]:
A - B

array([-4, -4, -4, -4])

In [7]:
A * B

array([ 5, 12, 21, 32])

In [8]:
A / B

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [9]:
A + 3

array([4, 5, 6, 7])

In [10]:
A - 2

array([-1,  0,  1,  2])

In [11]:
2 * A

array([2, 4, 6, 8])

In [12]:
abs(A)

array([1, 2, 3, 4])

In [13]:
A + 3*B

array([16, 20, 24, 28])

In [14]:
np.add(A,B)

array([ 6,  8, 10, 12])

In [15]:
np.subtract(A,B)

array([-4, -4, -4, -4])

In [16]:
np.multiply(A,B)

array([ 5, 12, 21, 32])

In [17]:
np.divide(A,B)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

## Matrix operations

In [20]:
x = np.array([[1, 3], [-2, 0]])
y = np.array([[6, 0], [-1, 2]])

In [22]:
x * y

array([[6, 0],
       [2, 0]])

In [23]:
np.dot(x,y)

array([[  3,   6],
       [-12,   0]])