#### Pseudo random generator

In [2]:
import numpy as np

In [4]:
np.random.seed(0)

In [9]:
np.random.randn()

0.12167501649282841

In [11]:
np.random.randn(10)

array([ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921,
        1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647])

In [12]:
np.random.randn(10,4)

array([[-0.34791215,  0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028],
       [-0.89546656,  0.3869025 , -0.51080514, -1.18063218],
       [-0.02818223,  0.42833187,  0.06651722,  0.3024719 ],
       [-0.63432209, -0.36274117, -0.67246045, -0.35955316],
       [-0.81314628, -1.7262826 ,  0.17742614, -0.40178094],
       [-1.63019835,  0.46278226, -0.90729836,  0.0519454 ],
       [ 0.72909056,  0.12898291,  1.13940068, -1.23482582]])

In [14]:
np.random.rand()

0.7163272041185655

In [15]:
np.random.rand(10)

array([0.28940609, 0.18319136, 0.58651293, 0.02010755, 0.82894003,
       0.00469548, 0.67781654, 0.27000797, 0.73519402, 0.96218855])

In [16]:
np.random.rand(10,4)

array([[0.24875314, 0.57615733, 0.59204193, 0.57225191],
       [0.22308163, 0.95274901, 0.44712538, 0.84640867],
       [0.69947928, 0.29743695, 0.81379782, 0.39650574],
       [0.8811032 , 0.58127287, 0.88173536, 0.69253159],
       [0.72525428, 0.50132438, 0.95608363, 0.6439902 ],
       [0.42385505, 0.60639321, 0.0191932 , 0.30157482],
       [0.66017354, 0.29007761, 0.61801543, 0.4287687 ],
       [0.13547406, 0.29828233, 0.56996491, 0.59087276],
       [0.57432525, 0.65320082, 0.65210327, 0.43141844],
       [0.8965466 , 0.36756187, 0.43586493, 0.89192336]])

In [17]:
np.random.randint(10)

5

In [18]:
np.random.randint(low=10, high=101)

97

In [19]:
np.random.randint(low=10, high=101, size=10)

array([53, 42, 21, 94, 20, 64, 47, 38, 12, 37])

In [20]:
np.random.choice([4,5,1,7,3,6])

7

In [21]:
np.random.choice(['python','java','sql'])

'java'

In [23]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.random.shuffle(data)

In [25]:
data

array([0, 2, 1, 8, 9, 4, 6, 3, 5, 7])