#### Indexing and slicing

In [1]:
import numpy as np

In [3]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
A[:5]

array([0, 1, 2, 3, 4])

In [6]:
A[2:16:3]

array([ 2,  5,  8, 11, 14])

In [7]:
A[13]

13

In [8]:
A[-5]

15

In [10]:
A = A.reshape(4,5)

In [11]:
A[0]

array([0, 1, 2, 3, 4])

In [13]:
A[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
A[:, 2]

array([ 2,  7, 12, 17])

In [15]:
A[:, -1]

array([ 4,  9, 14, 19])

In [17]:
A[2,2]

12

In [18]:
A[2,:]

array([10, 11, 12, 13, 14])

In [19]:
A[1:3,1:3]

array([[ 6,  7],
       [11, 12]])