## Algebra

In [2]:
import numpy as np

#### Vector norm

In [5]:
v1 = np.array([-2,4])
v1

array([-2,  4])

In [6]:
np.linalg.norm(v1)

4.47213595499958

#### Vector norm in Rn

In [7]:
v2 = np.array([2,5,7])
v2

array([2, 5, 7])

In [8]:
np.linalg.norm(v2)

8.831760866327848

#### Distance between two points

In [9]:
p1 = np.array([1,1])
p2 = np.array([10,5])
print(p1)
print(p2)

[1 1]
[10  5]


In [11]:
np.linalg.norm(p1 - p2)

9.848857801796104

In [12]:
p3 = np.array([3,4,10])
p4 = np.array([-1,6,30])
np.linalg.norm(p3-p4)

20.493901531919196

#### Matrix multipling

In [14]:
X = np.array([[5,3],[3,9]])
Y = np.array([[1],[-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [20]:
Z = X.dot(Y)
print(Z)

[[ 2]
 [-6]]


In [21]:
U = Y.dot(X)
print(U)

ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [22]:
Z.shape

(2, 1)

In [24]:
W = np.array([[2, -1, 3],
              [3, 1, 0]])
V = np.array([[2,1,-1],
              [0,-1,2],
              [3,2,0]])
print(W,'\n')
print(V)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [26]:
T = np.dot(W,V)
T

array([[13,  9, -4],
       [ 6,  2, -1]])

#### Properties of Matrix

In [28]:
A = np.array([[2,4],[-1,3]])
A

array([[ 2,  4],
       [-1,  3]])

In [30]:
round(np.linalg.det(A))

10.0

In [33]:
np.trace(A)

5

In [34]:
B = np.eye(3)
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
print(B,'\n')
print(B.T)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
print(A,'\n')
print(A.T)

[[ 2  4]
 [-1  3]] 

[[ 2 -1]
 [ 4  3]]


In [40]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

#### System of equations

In [41]:
A = np.array([[2,4],[1,-1]])
B = np.array([[10],[-1]])
print(A)
print(B)

[[ 2  4]
 [ 1 -1]]
[[10]
 [-1]]


In [42]:
A_int = np.linalg.inv(A)

In [44]:
X = np.dot(A_int,B)
X

array([[1.],
       [2.]])