## Statistic functions

In [1]:
import numpy as np

In [2]:
price = np.array([[12.4, 12.8, 11.9, 12.6, 1000],
                  [12.5, 13.0, 11.7, 12.2, 2000],
                  [12.2, 13.4, 12.2, 13.2, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [3]:
price.sum()

4650.1

In [4]:
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [5]:
price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

In [6]:
np.sum(price)

4650.1

In [7]:
np.min(price)

11.7

In [8]:
np.max(price)

2000.0

In [10]:
np.median(price)

12.6

In [14]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

In [12]:
np.std(price)

622.3781502877133

In [13]:
np.var(price)

387354.5619555555

In [15]:
np.random.rand(10)

array([0.83556959, 0.86950353, 0.54204667, 0.69216242, 0.36595912,
       0.91094459, 0.9749949 , 0.41732003, 0.20731358, 0.01614263])

In [16]:
np.random.randn(10)

array([ 0.28459435,  1.05026684, -0.62372741, -0.40043587, -0.9580312 ,
        0.60563144, -0.67208285, -0.29763078, -0.60246668,  0.10068584])

In [18]:
np.random.l

AttributeError: module 'numpy.random' has no attribute 'linspace'